version: '3.8'

services:
  # Moteur PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: famillereligieuse_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    depends_on:
      - db
    networks:
      - fr_network

  # Serveur Web Nginx
  nginx:
    image: nginx:alpine
    container_name: famillereligieuse_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - fr_network

  # Base de donn√©es MySQL
  db:
    image: mysql:8.0
    container_name: famillereligieuse_db
    restart: always
    environment:
      MYSQL_DATABASE: famille_religieuse
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - fr_db_data:/var/lib/mysql
    networks:
      - fr_network

networks:
  fr_network:
    driver: bridge

volumes:
  fr_db_data: